FROM codeberg.org/forgejo/forgejo:1.21



# ARG DB_HEALTHCHECK_INTERVAL
# ARG DB_HEALTHCHECK_TIMEOUT
# ARG DB_HEALTHCHECK_RETRIES

# # Healthcheck for Forgejo
# ARG FORGEJO_HEALTHCHECK_INTERVAL
# ARG FORGEJO_HEALTHCHECK_TIMEOUT
# ARG FORGEJO_HEALTHCHECK_RETRIES



# ARG FORGEJO_DB_USER
# ARG FORGEJO_DB_PASSWORD
# ARG FORGEJO_DB_NAME
# ARG FORGEJO_DB_HOST
# ARG FORGEJO_DB_PORT

# # Forgejo
# ARG FORGEJO_SSH_PORT
# ARG FORGEJO_HTTP_PORT


# ARG SMTP_HOST
# ARG SMTP_PORT
# ARG SMTP_USER
# ARG SMTP_PASSWORD
# ARG SMTP_FROM
# ARG SMTP_TLS



# ENV DB_HEALTHCHECK_INTERVAL=$DB_HEALTHCHECK_INTERVAL
# ENV DB_HEALTHCHECK_TIMEOUT=$DB_HEALTHCHECK_TIMEOUT
# ENV DB_HEALTHCHECK_RETRIES=$DB_HEALTHCHECK_RETRIES
# ENV FORGEJO_HEALTHCHECK_INTERVAL=$FORGEJO_HEALTHCHECK_INTERVAL
# ENV FORGEJO_HEALTHCHECK_TIMEOUT=$FORGEJO_HEALTHCHECK_TIMEOUT
# ENV FORGEJO_HEALTHCHECK_RETRIES=$FORGEJO_HEALTHCHECK_RETRIES
# ENV FORGEJO_DB_USER=$FORGEJO_DB_USER
# ENV FORGEJO_DB_PASSWORD=$FORGEJO_DB_PASSWORD
# ENV FORGEJO_DB_NAME=$FORGEJO_DB_NAME
# ENV FORGEJO_DB_HOST=$FORGEJO_DB_HOST
# ENV FORGEJO_DB_PORT=$FORGEJO_DB_PORT
# ENV FORGEJO_SSH_PORT=$FORGEJO_SSH_PORT
# ENV FORGEJO_HTTP_PORT=$FORGEJO_HTTP_PORT
# ENV SMTP_HOST=$SMTP_HOST
# ENV SMTP_PORT=$SMTP_PORT
# ENV SMTP_USER=$SMTP_USER
# ENV SMTP_PASSWORD=$SMTP_PASSWORD
# ENV SMTP_FROM=$SMTP_FROM
# ENV SMTP_TLS=$SMTP_TLS








# # ENV ADD_CO_COMMITTER_TRAILERS=$ADD_CO_COMMITTER_TRAILERS
# # ENV ALLOW_ADOPTION_OF_UNADOPTED_REPOSITORIES=$ALLOW_ADOPTION_OF_UNADOPTED_REPOSITORIES
# # ENV ALLOW_DELETION_OF_UNADOPTED_REPOSITORIES=$ALLOW_DELETION_OF_UNADOPTED_REPOSITORIES
# # ENV ALLOW_FORK_WITHOUT_MAXIMUM_LIMIT=$ALLOW_FORK_WITHOUT_MAXIMUM_LIMIT
# # ENV ALLOW_ONLY_EXTERNAL_REGISTRATION=$ALLOW_ONLY_EXTERNAL_REGISTRATION
# # ENV ALLOW_ONLY_INTERNAL_REGISTRATION=$ALLOW_ONLY_INTERNAL_REGISTRATION
# # ENV AMBIGUOUS_UNICODE_DETECTION=$AMBIGUOUS_UNICODE_DETECTION
# # ENV DEFAULT_BRANCH=$DEFAULT_BRANCH
# # ENV DEFAULT_EMAIL_NOTIFICATIONS=$DEFAULT_EMAIL_NOTIFICATIONS
# # ENV DEFAULT_MERGE_MESSAGE_ALL_AUTHORS=$DEFAULT_MERGE_MESSAGE_ALL_AUTHORS
# # ENV DEFAULT_MERGE_MESSAGE_COMMITS_LIMIT=$DEFAULT_MERGE_MESSAGE_COMMITS_LIMIT
# # ENV DEFAULT_MERGE_MESSAGE_MAX_APPROVERS=$DEFAULT_MERGE_MESSAGE_MAX_APPROVERS
# # ENV DEFAULT_MERGE_MESSAGE_SIZE=$DEFAULT_MERGE_MESSAGE_SIZE
# # ENV DEFAULT_MERGE_STYLE=$DEFAULT_MERGE_STYLE
# # ENV DEFAULT_ORG_MEMBER_VISIBLE=$DEFAULT_ORG_MEMBER_VISIBLE
# # ENV DISABLE_DIFF_HIGHLIGHT=$DISABLE_DIFF_HIGHLIGHT
# # ENV DISABLE_DOWNLOAD_SOURCE_ARCHIVES=$DISABLE_DOWNLOAD_SOURCE_ARCHIVES
# # ENV DISABLE_SSH=$DISABLE_SSH
# # ENV DISABLE_WEBHOOKS=$DISABLE_WEBHOOKS
# # ENV ENABLED_ISSUE_BY_LABEL=$ENABLED_ISSUE_BY_LABEL
# # ENV ENABLED_ISSUE_BY_REPOSITORY=$ENABLED_ISSUE_BY_REPOSITORY
# # ENV ENABLE_AUTO_REGISTRATION=$ENABLE_AUTO_REGISTRATION
# # ENV ENABLE_CAPTCHA=$ENABLE_CAPTCHA
# # ENV ENABLE_FEED=$ENABLE_FEED
# # ENV ENABLE_OPENID_SIGNIN=$ENABLE_OPENID_SIGNIN
# # ENV ENABLE_OPENID_SIGNUP=$ENABLE_OPENID_SIGNUP
# # ENV ENABLE_REVERSE_PROXY_AUTHENTICATION=$ENABLE_REVERSE_PROXY_AUTHENTICATION
# # ENV ENABLE_SITEMAP=$ENABLE_SITEMAP
# # ENV FORGEJO_ACTIONS_ENABLED=$FORGEJO_ACTIONS_ENABLED
# # ENV FORGEJO_APP_DATA_PATH=$FORGEJO_APP_DATA_PATH
# # ENV FORGEJO_APP_NAME=$FORGEJO_APP_NAME
# # ENV FORGEJO_DB_HOST=$FORGEJO_DB_HOST
# # ENV FORGEJO_DB_NAME=$FORGEJO_DB_NAME
# # ENV FORGEJO_DB_PASSWORD=$FORGEJO_DB_PASSWORD
# # ENV FORGEJO_DB_PORT=$FORGEJO_DB_PORT
# # ENV FORGEJO_DB_TYPE=$FORGEJO_DB_TYPE
# # ENV FORGEJO_DB_USER=$FORGEJO_DB_USER
# # ENV FORGEJO_DISABLE_REGISTRATION=$FORGEJO_DISABLE_REGISTRATION
# # ENV FORGEJO_DOMAIN=$FORGEJO_DOMAIN
# # ENV FORGEJO_FEDERATION_ENABLED=$FORGEJO_FEDERATION_ENABLED
# # ENV FORGEJO_HTTP_PORT=$FORGEJO_HTTP_PORT
# # ENV FORGEJO_INSTALL_LOCK=$FORGEJO_INSTALL_LOCK
# # ENV FORGEJO_INTERNAL_TOKEN=$FORGEJO_INTERNAL_TOKEN
# # ENV FORGEJO_LFS_CONTENT_PATH=$FORGEJO_LFS_CONTENT_PATH
# # ENV FORGEJO_LFS_JWT_SECRET=$FORGEJO_LFS_JWT_SECRET
# # ENV FORGEJO_MAILER_ENABLED=$FORGEJO_MAILER_ENABLED
# # ENV FORGEJO_MAILER_FROM=$FORGEJO_MAILER_FROM
# # ENV FORGEJO_MAILER_HOST=$FORGEJO_MAILER_HOST
# # ENV FORGEJO_MAILER_PASSWD=$FORGEJO_MAILER_PASSWD
# # ENV FORGEJO_MAILER_PORT=$FORGEJO_MAILER_PORT
# # ENV FORGEJO_MAILER_USER=$FORGEJO_MAILER_USER
# # ENV FORGEJO_OAUTH2_JWT_SECRET=$FORGEJO_OAUTH2_JWT_SECRET
# # ENV FORGEJO_REPOSITORY_ROOT=$FORGEJO_REPOSITORY_ROOT
# # ENV FORGEJO_ROOT_URL=$FORGEJO_ROOT_URL
# # ENV FORGEJO_RUN_MODE=$FORGEJO_RUN_MODE
# # ENV FORGEJO_RUN_USER=$FORGEJO_RUN_USER
# # ENV FORGEJO_SECRET_KEY=$FORGEJO_SECRET_KEY
# # ENV FORGEJO_SMTP_TLS=$FORGEJO_SMTP_TLS
# # ENV FORGEJO_SSH_DOMAIN=$FORGEJO_SSH_DOMAIN
# # ENV FORGEJO_SSH_PORT=$FORGEJO_SSH_PORT
# # ENV LINE_WRAP_EXTENSIONS=$LINE_WRAP_EXTENSIONS
# # ENV MAX_TIMEOUT=$MAX_TIMEOUT
# # ENV METRICS_ENABLED=$METRICS_ENABLED
# # ENV METRICS_ENABLED_ISSUE_BY_LABEL=$METRICS_ENABLED_ISSUE_BY_LABEL
# # ENV METRICS_ENABLED_ISSUE_BY_REPOSITORY=$METRICS_ENABLED_ISSUE_BY_REPOSITORY
# # ENV MIN_PASSWORD_LENGTH=$MIN_PASSWORD_LENGTH
# # ENV NOTICE_PAGING_NUM=$NOTICE_PAGING_NUM
# # ENV ORG_PAGING_NUM=$ORG_PAGING_NUM
# # ENV PREVIEWABLE_FILE_MODES=$PREVIEWABLE_FILE_MODES
# # ENV PROJECT_BOARD_BASIC_KANBAN_TYPE=$PROJECT_BOARD_BASIC_KANBAN_TYPE
# # ENV REGISTER_EMAIL_CONFIRM=$REGISTER_EMAIL_CONFIRM
# # ENV REPO_PAGING_NUM=$REPO_PAGING_NUM
# # ENV RESPOSITORY_HEALTH_CHECK_SCHEDULE=$RESPOSITORY_HEALTH_CHECK_SCHEDULE
# # ENV RETARGET_CHILDREN_ON_MERGE=$RETARGET_CHILDREN_ON_MERGE
# # ENV SHOW_FOOTER_POWERED_BY=$SHOW_FOOTER_POWERED_BY
# # ENV SHOW_FOOTER_TEMPLATE_LOAD_TIME=$SHOW_FOOTER_TEMPLATE_LOAD_TIME
# # ENV SHOW_FOOTER_VERSION=$SHOW_FOOTER_VERSION
# # ENV SSH_EXPOSE_ANONYMOUS=$SSH_EXPOSE_ANONYMOUS
# # ENV SSH_KEYGEN_PATH=$SSH_KEYGEN_PATH
# # ENV START_SSH_SERVER=$START_SSH_SERVER
# # ENV TIMEOUT_STEP=$TIMEOUT_STEP
# # ENV UPDATE_AVATAR=$UPDATE_AVATAR
# # ENV USER_GID=$USER_GID
# # ENV USER_PAGING_NUM=$USER_PAGING_NUM
# # ENV USER_UID=$USER_UID




# Base image for Forgejo (adjust to your needs)
FROM alpine:3.20

# Set work directory
WORKDIR /app

# Accept all build arguments dynamically (from your CI/CD)
# Note: You need to list them here exactly as in BUILD_ARG_KEYS
ARG ADD_CO_COMMITTER_TRAILERS
ARG ALLOW_ADOPTION_OF_UNADOPTED_REPOSITORIES
ARG ALLOW_DELETION_OF_UNADOPTED_REPOSITORIES
ARG ALLOW_FORK_WITHOUT_MAXIMUM_LIMIT
ARG ALLOW_ONLY_EXTERNAL_REGISTRATION
ARG ALLOW_ONLY_INTERNAL_REGISTRATION
ARG AMBIGUOUS_UNICODE_DETECTION
ARG DEFAULT_BRANCH
ARG DEFAULT_EMAIL_NOTIFICATIONS
ARG DEFAULT_MERGE_MESSAGE_ALL_AUTHORS
ARG DEFAULT_MERGE_MESSAGE_COMMITS_LIMIT
ARG DEFAULT_MERGE_MESSAGE_MAX_APPROVERS
ARG DEFAULT_MERGE_MESSAGE_SIZE
ARG DEFAULT_MERGE_STYLE
ARG DEFAULT_ORG_MEMBER_VISIBLE
ARG DISABLE_DIFF_HIGHLIGHT
ARG DISABLE_DOWNLOAD_SOURCE_ARCHIVES
ARG DISABLE_SSH
ARG DISABLE_WEBHOOKS
ARG ENABLED_ISSUE_BY_LABEL
ARG ENABLED_ISSUE_BY_REPOSITORY
ARG ENABLE_AUTO_REGISTRATION
ARG ENABLE_CAPTCHA
ARG ENABLE_FEED
ARG ENABLE_OPENID_SIGNIN
ARG ENABLE_OPENID_SIGNUP
ARG ENABLE_REVERSE_PROXY_AUTHENTICATION
ARG ENABLE_SITEMAP
ARG FORGEJO_ACTIONS_ENABLED
ARG FORGEJO_APP_DATA_PATH
ARG FORGEJO_APP_NAME
ARG FORGEJO_DB_HOST
ARG FORGEJO_DB_NAME
ARG FORGEJO_DB_PASSWORD
ARG FORGEJO_DB_PORT
ARG FORGEJO_DB_TYPE
ARG FORGEJO_DB_USER
ARG FORGEJO_DISABLE_REGISTRATION
ARG FORGEJO_DOMAIN
ARG FORGEJO_FEDERATION_ENABLED
ARG FORGEJO_HTTP_PORT
ARG FORGEJO_INSTALL_LOCK
ARG FORGEJO_INTERNAL_TOKEN
ARG FORGEJO_LFS_CONTENT_PATH
ARG FORGEJO_LFS_JWT_SECRET
ARG FORGEJO_MAILER_ENABLED
ARG FORGEJO_MAILER_FROM
ARG FORGEJO_MAILER_HOST
ARG FORGEJO_MAILER_PASSWD
ARG FORGEJO_MAILER_PORT
ARG FORGEJO_MAILER_USER
ARG FORGEJO_OAUTH2_JWT_SECRET
ARG FORGEJO_REPOSITORY_ROOT
ARG FORGEJO_ROOT_URL
ARG FORGEJO_RUN_MODE
ARG FORGEJO_RUN_USER
ARG FORGEJO_SECRET_KEY
ARG FORGEJO_SMTP_TLS
ARG FORGEJO_SSH_DOMAIN
ARG FORGEJO_SSH_PORT
ARG LINE_WRAP_EXTENSIONS
ARG MAX_TIMEOUT
ARG METRICS_ENABLED
ARG METRICS_ENABLED_ISSUE_BY_LABEL
ARG METRICS_ENABLED_ISSUE_BY_REPOSITORY
ARG MIN_PASSWORD_LENGTH
ARG NOTICE_PAGING_NUM
ARG ORG_PAGING_NUM
ARG PREVIEWABLE_FILE_MODES
ARG PROJECT_BOARD_BASIC_KANBAN_TYPE
ARG REGISTER_EMAIL_CONFIRM
ARG REPO_PAGING_NUM
ARG REPOSITORY_HEALTH_CHECK_SCHEDULE
ARG RETARGET_CHILDREN_ON_MERGE
ARG SHOW_FOOTER_POWERED_BY
ARG SHOW_FOOTER_TEMPLATE_LOAD_TIME
ARG SHOW_FOOTER_VERSION
ARG SSH_EXPOSE_ANONYMOUS
ARG SSH_KEYGEN_PATH
ARG START_SSH_SERVER
ARG TIMEOUT_STEP
ARG UPDATE_AVATAR
ARG USER_GID
ARG USER_PAGING_NUM
ARG USER_UID

# Convert build args to environment variables in the container
# This way Forgejo can read them directly at runtime
ENV ADD_CO_COMMITTER_TRAILERS=${ADD_CO_COMMITTER_TRAILERS} \
    ALLOW_ADOPTION_OF_UNADOPTED_REPOSITORIES=${ALLOW_ADOPTION_OF_UNADOPTED_REPOSITORIES} \
    ALLOW_DELETION_OF_UNADOPTED_REPOSITORIES=${ALLOW_DELETION_OF_UNADOPTED_REPOSITORIES} \
    ALLOW_FORK_WITHOUT_MAXIMUM_LIMIT=${ALLOW_FORK_WITHOUT_MAXIMUM_LIMIT} \
    ALLOW_ONLY_EXTERNAL_REGISTRATION=${ALLOW_ONLY_EXTERNAL_REGISTRATION} \
    ALLOW_ONLY_INTERNAL_REGISTRATION=${ALLOW_ONLY_INTERNAL_REGISTRATION} \
    AMBIGUOUS_UNICODE_DETECTION=${AMBIGUOUS_UNICODE_DETECTION} \
    DEFAULT_BRANCH=${DEFAULT_BRANCH} \
    DEFAULT_EMAIL_NOTIFICATIONS=${DEFAULT_EMAIL_NOTIFICATIONS} \
    DEFAULT_MERGE_MESSAGE_ALL_AUTHORS=${DEFAULT_MERGE_MESSAGE_ALL_AUTHORS} \
    DEFAULT_MERGE_MESSAGE_COMMITS_LIMIT=${DEFAULT_MERGE_MESSAGE_COMMITS_LIMIT} \
    DEFAULT_MERGE_MESSAGE_MAX_APPROVERS=${DEFAULT_MERGE_MESSAGE_MAX_APPROVERS} \
    DEFAULT_MERGE_MESSAGE_SIZE=${DEFAULT_MERGE_MESSAGE_SIZE} \
    DEFAULT_MERGE_STYLE=${DEFAULT_MERGE_STYLE} \
    DEFAULT_ORG_MEMBER_VISIBLE=${DEFAULT_ORG_MEMBER_VISIBLE} \
    DISABLE_DIFF_HIGHLIGHT=${DISABLE_DIFF_HIGHLIGHT} \
    DISABLE_DOWNLOAD_SOURCE_ARCHIVES=${DISABLE_DOWNLOAD_SOURCE_ARCHIVES} \
    DISABLE_SSH=${DISABLE_SSH} \
    DISABLE_WEBHOOKS=${DISABLE_WEBHOOKS} \
    ENABLED_ISSUE_BY_LABEL=${ENABLED_ISSUE_BY_LABEL} \
    ENABLED_ISSUE_BY_REPOSITORY=${ENABLED_ISSUE_BY_REPOSITORY} \
    ENABLE_AUTO_REGISTRATION=${ENABLE_AUTO_REGISTRATION} \
    ENABLE_CAPTCHA=${ENABLE_CAPTCHA} \
    ENABLE_FEED=${ENABLE_FEED} \
    ENABLE_OPENID_SIGNIN=${ENABLE_OPENID_SIGNIN} \
    ENABLE_OPENID_SIGNUP=${ENABLE_OPENID_SIGNUP} \
    ENABLE_REVERSE_PROXY_AUTHENTICATION=${ENABLE_REVERSE_PROXY_AUTHENTICATION} \
    ENABLE_SITEMAP=${ENABLE_SITEMAP} \
    FORGEJO_ACTIONS_ENABLED=${FORGEJO_ACTIONS_ENABLED} \
    FORGEJO_APP_DATA_PATH=${FORGEJO_APP_DATA_PATH} \
    FORGEJO_APP_NAME=${FORGEJO_APP_NAME} \
    FORGEJO_DB_HOST=${FORGEJO_DB_HOST} \
    FORGEJO_DB_NAME=${FORGEJO_DB_NAME} \
    FORGEJO_DB_PASSWORD=${FORGEJO_DB_PASSWORD} \
    FORGEJO_DB_PORT=${FORGEJO_DB_PORT} \
    FORGEJO_DB_TYPE=${FORGEJO_DB_TYPE} \
    FORGEJO_DB_USER=${FORGEJO_DB_USER} \
    FORGEJO_DISABLE_REGISTRATION=${FORGEJO_DISABLE_REGISTRATION} \
    FORGEJO_DOMAIN=${FORGEJO_DOMAIN} \
    FORGEJO_FEDERATION_ENABLED=${FORGEJO_FEDERATION_ENABLED} \
    FORGEJO_HTTP_PORT=${FORGEJO_HTTP_PORT} \
    FORGEJO_INSTALL_LOCK=${FORGEJO_INSTALL_LOCK} \
    FORGEJO_INTERNAL_TOKEN=${FORGEJO_INTERNAL_TOKEN} \
    FORGEJO_LFS_CONTENT_PATH=${FORGEJO_LFS_CONTENT_PATH} \
    FORGEJO_LFS_JWT_SECRET=${FORGEJO_LFS_JWT_SECRET} \
    FORGEJO_MAILER_ENABLED=${FORGEJO_MAILER_ENABLED} \
    FORGEJO_MAILER_FROM=${FORGEJO_MAILER_FROM} \
    FORGEJO_MAILER_HOST=${FORGEJO_MAILER_HOST} \
    FORGEJO_MAILER_PASSWD=${FORGEJO_MAILER_PASSWD} \
    FORGEJO_MAILER_PORT=${FORGEJO_MAILER_PORT} \
    FORGEJO_MAILER_USER=${FORGEJO_MAILER_USER} \
    FORGEJO_OAUTH2_JWT_SECRET=${FORGEJO_OAUTH2_JWT_SECRET} \
    FORGEJO_REPOSITORY_ROOT=${FORGEJO_REPOSITORY_ROOT} \
    FORGEJO_ROOT_URL=${FORGEJO_ROOT_URL} \
    FORGEJO_RUN_MODE=${FORGEJO_RUN_MODE} \
    FORGEJO_RUN_USER=${FORGEJO_RUN_USER} \
    FORGEJO_SECRET_KEY=${FORGEJO_SECRET_KEY} \
    FORGEJO_SMTP_TLS=${FORGEJO_SMTP_TLS} \
    FORGEJO_SSH_DOMAIN=${FORGEJO_SSH_DOMAIN} \
    FORGEJO_SSH_PORT=${FORGEJO_SSH_PORT} \
    LINE_WRAP_EXTENSIONS=${LINE_WRAP_EXTENSIONS} \
    MAX_TIMEOUT=${MAX_TIMEOUT} \
    METRICS_ENABLED=${METRICS_ENABLED} \
    METRICS_ENABLED_ISSUE_BY_LABEL=${METRICS_ENABLED_ISSUE_BY_LABEL} \
    METRICS_ENABLED_ISSUE_BY_REPOSITORY=${METRICS_ENABLED_ISSUE_BY_REPOSITORY} \
    MIN_PASSWORD_LENGTH=${MIN_PASSWORD_LENGTH} \
    NOTICE_PAGING_NUM=${NOTICE_PAGING_NUM} \
    ORG_PAGING_NUM=${ORG_PAGING_NUM} \
    PREVIEWABLE_FILE_MODES=${PREVIEWABLE_FILE_MODES} \
    PROJECT_BOARD_BASIC_KANBAN_TYPE=${PROJECT_BOARD_BASIC_KANBAN_TYPE} \
    REGISTER_EMAIL_CONFIRM=${REGISTER_EMAIL_CONFIRM} \
    REPO_PAGING_NUM=${REPO_PAGING_NUM} \
    REPOSITORY_HEALTH_CHECK_SCHEDULE=${REPOSITORY_HEALTH_CHECK_SCHEDULE} \
    RETARGET_CHILDREN_ON_MERGE=${RETARGET_CHILDREN_ON_MERGE} \
    SHOW_FOOTER_POWERED_BY=${SHOW_FOOTER_POWERED_BY} \
    SHOW_FOOTER_TEMPLATE_LOAD_TIME=${SHOW_FOOTER_TEMPLATE_LOAD_TIME} \
    SHOW_FOOTER_VERSION=${SHOW_FOOTER_VERSION} \
    SSH_EXPOSE_ANONYMOUS=${SSH_EXPOSE_ANONYMOUS} \
    SSH_KEYGEN_PATH=${SSH_KEYGEN_PATH} \
    START_SSH_SERVER=${START_SSH_SERVER} \
    TIMEOUT_STEP=${TIMEOUT_STEP} \
    UPDATE_AVATAR=${UPDATE_AVATAR} \
    USER_GID=${USER_GID} \
    USER_PAGING_NUM=${USER_PAGING_NUM} \
    USER_UID=${USER_UID}

# Copy Forgejo files into image
COPY . /app

# Expose Forgejo HTTP and SSH ports
EXPOSE ${FORGEJO_HTTP_PORT} ${FORGEJO_SSH_PORT}

# Command to run Forgejo
CMD ["./start.sh"]
